### ISSUE TITLE
Units Missing in Predictive and Historical metrics

### ISSUE THREAD

**Issue by mattiaslightstone** [Component-fi/perpetual-lp-tool#180] opened 2022-10-06 00:13 UTC
**Environment**
Browser: brave
OS: MacOS 13

**Steps to repro**
1. Enter dev.perpsim.com
2. Enter 100$ into the USD amount in the price/amount selection card

**Expected Behavior**
- Total Fees, Impermanent Loss, and Max Draw Down should have units specified as AAVE
- Perp rewards should possibly have units specified as PERP
- All four metrics should show the dollar value as well

**Actual behavior**
- Total Fees, Impermanent Loss, Max Draw Down and Perp Rewards all are unitless
- None of the metrics have USD values associated with them

**Screenshot**
<img width="347" alt="CleanShot 2022-10-05 at 17 13 43@2x" src="https://user-images.githubusercontent.com/87032785/194186045-7bcb52d9-cf5a-43f8-a6f8-d71224c8bc21.png">

**Comment by nickwang14** [comment] 2022-10-26 06:09
Fixed and duplicate of #188

**Closed by nickwang14** 2022-10-26 06:09 UTC
Labels: duplicate
